#!/bin/bash

SDKROOT=$IDA_SDK
unamestr=$(uname)
if [[ "$unamestr" == "Linux" ]]; then
  IDAROOT=$IDA_DIR
  OUTPUT="evm.plx"
  # 64 bit 
  OUTPUT64="evm.plx64
  ln -sf lib/linux_websockets.a websockets.a
elif [[ "$unamestr" == 'Darwin' ]]; then
  IDAROOT="/Applications/IDA Pro 7.6/idaq.app/Contents/MacOS/"
  OUTPUT="qira.pmc"
  OUTPUT64="qira.pmc64"
  ln -sf lib/mac_websockets.a linux_websockets.a
fi

if [[ "$unamestr" == "Linux" ]]; then
  strip $OUTPUT
  strip $OUTPUT64
fi

sha1sum $OUTPUT $OUTPUT^$
echo "Installing plugin!"
cp $OUTPUT "$IDAROOT/plugins"
cp $OUTPUT64 "$IDAROOT/plugins"

if [[ "$unamestr" == 'Linux' ]]; then
  cp $OUTPUT bin/evm_ida_linux.plx
  cp $OUTPUT64 bin/evm_ida_linux.plx64
elif [[ "$unamestr" == 'Darwin' ]]; then
  cp $OUTPUT bin/evm_ida_mac.pmc
  cp $OUTPUT64 bin/evm_ida_mac.pmc64
fi

