#!/bin/bash

SDKROOT=$IDA_SDK
unamestr=$(uname)
if [[ "$unamestr" == "Linux" ]]; then
  IDAROOT=$IDA_DIR
  OUTPUT="evm.plx"
  # 64 bit 
  OUTPUT64="evm.plx64
  ln -sf lib/linux_websockets.a websockets.a
elif [[ "$unamestr" == 'Darwin' ]]; then
  IDAROOT="/Applications/IDA Pro 7.6/idaq.app/Contents/MacOS/"
  OUTPUT="evm.pmc"
  OUTPUT64="evm.pmc64"
  ln -sf lib/mac_websockets.a websockets.a
fi
